### ISSUE TITLE
Are you going to release this as a plugin

### ISSUE THREAD

**Issue by bnussey** [AntonioCuevaUrraco/nativescript-mixpanel#1]
Hello just curious to see if you're going to release this as a plugin? We're looking at integrating Mixpanel so would love to know your plans.

**Comment by bnussey** [comment]
Happy to assist as contributor to help with this process.

**Comment by AntonioCuevaUrraco** [comment]
That's a great idea, I am already using this in my work app. I will wrap up
a bit as soon as I can and share the project with you. What I don't have
time for is to attend all the questions and issues that may raise with the
time.

**Comment by bnussey** [comment]
Hey @AntonioCuevaUrraco yep I can help with that. I also need it for my work app as well so happy to build out any extra functionality it requires. Is `identify` working for you?

**Comment by bnussey** [comment]
Nevermind got it all working. Have also added `timeEvent` so happy to do a push if you want to make me contributor and can also plugin-ify. Or can just submit a PR.

**Comment by AntonioCuevaUrraco** [comment]
I sent you an invite to collaborate. Also It was publish on npm from the beginning https://www.npmjs.com/package/nativescript-mixpanel

I can add you there as well if you need it

**Comment by bnussey** [comment]
Ah fantastic @AntonioCuevaUrraco didn't realise it was already released on there. Yep if you can add me on npm as well that would be great. thanks.

**Comment by bnussey** [comment]
Username is `bnussey`

**Comment by AntonioCuevaUrraco** [comment]
done

**Comment by RyanSMurphy** [comment]
@bnussey @AntonioCuevaUrraco does this work nativescript angular?

**Comment by bnussey** [comment]
Yes it does @RyanSMurphy
