### ISSUE TITLE
Is this repo supported?

### ISSUE THREAD

**Issue by RyanSMurphy** [AntonioCuevaUrraco/nativescript-mixpanel#3]
Hi, is this library currently being supported at all?

Thanks, 

Ryan

**Comment by bnussey** [comment]
Hi @RyanSMurphy I am attempting to support it.. Going to release an update in the next couple of weeks. What do you need?

**Comment by demetrio812** [comment]
I'm trying to support it too, just release a major update (2.0.1), cheers
