### ISSUE TITLE
Unable to use addPushDeviceToken()

### ISSUE THREAD

**Issue by faisal3389** [AntonioCuevaUrraco/nativescript-mixpanel#4]
I'm unable to use addPushDeviceToken() in my nativescript IOS application, it is throwing following exception: "libc++abi.dylib: terminating with uncaught exception of type NSException"

I'm using following verisons 
│ Component            │ Current version │ Latest version │ Information      │
│ nativescript           │ 2.5.3           │ 2.5.4          │ Update available │
│ tns-core-modules │ 2.5.0           │ 2.5.2          │ Update available │
│ tns-android            │ 2.5.0           │ 2.5.0          │ Up to date       │
│ tns-ios                    │ 2.5.0           │ 2.5.0          │ Up to date       

How do I register a device in nativescript ios application so that I can perform push notifications using mixpanel.

**Comment by demetrio812** [comment]
Hello, can you please try the latest version (2.0.1) and let me know if you still have problems? Also an example project would help...closing this for now but please reopen it in case you still have problems...cheers
