### ISSUE TITLE
The plugin doesn't support alias method 

### ISSUE THREAD

**Issue by alexandruantonica** [AntonioCuevaUrraco/nativescript-mixpanel#5]
The plugin doesn't support `alias` method and it should be useful. 

What do you think?
https://mixpanel.com/help/reference/javascript#user-identity

**Comment by bnussey** [comment]
Hi @alexandruantonica I've actually just done it for iOS a few days ago.. Android to come soon.

**Comment by alexandruantonica** [comment]
@bnussey Thanks man. 
Let me know, please.

**Comment by bnussey** [comment]
Hi @alexandruantonica just added `alias` for Android .. please test and advise if any issues
