### ISSUE TITLE
Version 2.0.0 of the npm package is empty

### ISSUE THREAD

**Issue by demetrio812** [AntonioCuevaUrraco/nativescript-mixpanel#7]
Hello,
I've tried to use the 2.0.0 version and this is the package I get:

<img width="249" alt="screenshot 2017-10-04 20 04 02" src="https://user-images.githubusercontent.com/385644/31197664-b729917a-a949-11e7-9709-2f3d32b33732.png">

It looks like you didn't build and prepare the plugin before creating and uploading the package...

Can you please double check and release a new version?

You have to go inside `src` and run `npm run plugin.prepare`

After that you go in `publish` and pack + publish the plugin...I'm not sure if it will override the current version or if it requires a new versione...

Let me know...

Thanks,
Dem

**Comment by AntonioCuevaUrraco** [comment]
@demetrio812 I have little time to work on NativeScript this days as I am working on Native now.

I added you to npm as collaborator as well so you can take over(most of the work on this plug in is yours anyway :-) )

**Comment by demetrio812** [comment]
@AntonioCuevaUrraco thank you, just published version 2.0.1, cheers!
